Repository echo-webkom/echo-web-backend, pull requests merged in 2021-09, with the labels that each got.

#122 Waitlist spot response (master)
  src/main/kotlin/no/uib/echo/Response.kt
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/Registration.kt
  src/test/kotlin/no/uib/echo/BedpresRegistrationTest.kt
  src/test/kotlin/no/uib/echo/EventRegistrationTest.kt
Labels: feature :sparkles:, minor :arrow_up_small:

#126 💚 Add workflow cache for faster CI
  .dockerignore
  .github/workflows/cypress_test_dev.yaml
  .github/workflows/cypress_test_prod.yaml
  .github/workflows/kotest_test.yaml
  docker-compose.ci.yaml
  docker-compose.kotest.yaml
Labels: devops :rocket:, refactoring :recycle:

#130 🍻 Implement MVP for Bekk registration
  src/main/kotlin/no/uib/echo/schema/Registration.kt
  src/test/kotlin/no/uib/echo/BedpresRegistrationTest.kt
Labels: feature :sparkles:, patch :mag:

#131 Patch
  .dockerignore
  .github/workflows/cypress_test_dev.yaml
  .github/workflows/cypress_test_prod.yaml
  .github/workflows/kotest_test.yaml
  build.gradle.kts
  docker-compose.ci.yaml
  docker-compose.kotest.yaml
  gradle.properties
  src/main/kotlin/no/uib/echo/schema/Registration.kt
  src/test/kotlin/no/uib/echo/BedpresRegistrationTest.kt
Labels: patch :mag:

#132 🚑 Update spots
  src/main/kotlin/no/uib/echo/schema/Registration.kt
Labels: patch :mag:

#134 ♻️ Remove MVP code for Bekk registration
  src/main/kotlin/no/uib/echo/schema/Registration.kt
  src/test/kotlin/no/uib/echo/BedpresRegistrationTest.kt
Labels: refactoring :recycle:, patch :mag:

#135 ⚡️ Increase max connections in DB pool
  src/main/kotlin/no/uib/echo/Database.kt
Labels: database :desktop_computer:, patch :mag:

#141 🐛 Specify same JVM version for Java and Kotlin
  build.gradle.kts
Labels: bug :bug:, patch :mag:

#140 ♻️ Combine BEDKOM_KEY and WEBKOM_KEY to single env
  .env.example
  .github/workflows/cypress_test_dev.yaml
  .github/workflows/cypress_test_prod.yaml
  .gitignore
  docker-compose.ci.yaml
  docker-compose.cypress.yaml
  docker-compose.kotest.yaml
  docker-compose.yaml
  scripts/delete_happening
  scripts/delete_registration
  scripts/get_count_registrations
  scripts/get_registrations
  scripts/submit_happening
  src/main/kotlin/no/uib/echo/Application.kt
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/test/kotlin/no/uib/echo/BedpresRegistrationTest.kt
  src/test/kotlin/no/uib/echo/BedpresTest.kt
  src/test/kotlin/no/uib/echo/EventRegistrationTest.kt
  src/test/kotlin/no/uib/echo/EventTest.kt
Labels: refactoring :recycle:, major :arrow_double_up:

#139 ♻️ Rename HAPPENINGTYPE and WAITLIST to name with _
  src/main/kotlin/no/uib/echo/Response.kt
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/Answer.kt
  src/main/kotlin/no/uib/echo/schema/Happening.kt
  src/main/kotlin/no/uib/echo/schema/Registration.kt
  src/test/kotlin/no/uib/echo/BedpresRegistrationTest.kt
  src/test/kotlin/no/uib/echo/BedpresTest.kt
  src/test/kotlin/no/uib/echo/EventRegistrationTest.kt
  src/test/kotlin/no/uib/echo/EventTest.kt
Labels: refactoring :recycle:, patch :mag:

#144 ♻️ Combine BEDKOM_KEY and WEBKOM_KEY to single env
  .env.example
  .github/workflows/cypress_test_dev.yaml
  .github/workflows/cypress_test_prod.yaml
  .gitignore
  docker-compose.ci.yaml
  docker-compose.cypress.yaml
  docker-compose.kotest.yaml
  docker-compose.yaml
  scripts/delete_happening
  scripts/delete_registration
  scripts/get_count_registrations
  scripts/get_registrations
  scripts/submit_happening
  src/main/kotlin/no/uib/echo/Application.kt
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/test/kotlin/no/uib/echo/BedpresRegistrationTest.kt
  src/test/kotlin/no/uib/echo/BedpresTest.kt
  src/test/kotlin/no/uib/echo/EventRegistrationTest.kt
  src/test/kotlin/no/uib/echo/EventTest.kt
Labels: refactoring :recycle:, major :arrow_double_up:

#147 Release 5.0.0
  .env.example
  .github/workflows/cypress_test_dev.yaml
  .github/workflows/cypress_test_prod.yaml
  .gitignore
  Dockerfile
  build.gradle.kts
  docker-compose.ci.yaml
  docker-compose.cypress.yaml
  docker-compose.kotest.yaml
  docker-compose.yaml
  gradle.properties
  scripts/delete_happening
  scripts/delete_registration
  scripts/get_count_registrations
  scripts/get_registrations
  scripts/submit_happening
  src/main/kotlin/no/uib/echo/Application.kt
  src/main/kotlin/no/uib/echo/Database.kt
  src/main/kotlin/no/uib/echo/Response.kt
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/Answer.kt
  src/main/kotlin/no/uib/echo/schema/Happening.kt
  src/main/kotlin/no/uib/echo/schema/Registration.kt
  src/main/kotlin/no/uib/echo/schema/SpotRange.kt
  src/main/resources/db/migration/V5__Spot_ranges_and_generic.sql
  src/test/kotlin/no/uib/echo/BedpresRegistrationTest.kt
  src/test/kotlin/no/uib/echo/BedpresTest.kt
  src/test/kotlin/no/uib/echo/EventRegistrationTest.kt
  src/test/kotlin/no/uib/echo/EventTest.kt
  src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
  src/test/kotlin/no/uib/echo/HappeningTest.kt
Labels: major :arrow_double_up:

#149 🚑️ Fix wrong query for Happening
  src/main/kotlin/no/uib/echo/schema/Happening.kt
Labels: bug :bug:, database :desktop_computer:, patch :mag:

#150 Hotfix/wrong query
  src/main/kotlin/no/uib/echo/schema/Happening.kt
Labels: bug :bug:, database :desktop_computer:, patch :mag:
