Repository echo-webkom/echo-web-backend, pull requests merged in 2022-04, with the labels that each got.

#293 🍎 Fix broken Dockerfile on macOS
  Dockerfile
Labels: bug :bug:, patch :mag:

#298 🎨 Switch to kotlinx.serialization from Gson
  .env.example
  .github/workflows/cypress_test.yaml
  build.gradle.kts
  docker-compose.cypress.yaml
  src/main/kotlin/no/uib/echo/Email.kt
  src/main/kotlin/no/uib/echo/Response.kt
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/Answer.kt
  src/main/kotlin/no/uib/echo/schema/Happening.kt
  src/main/kotlin/no/uib/echo/schema/Registration.kt
  src/main/kotlin/no/uib/echo/schema/SpotRange.kt
  src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
  src/test/kotlin/no/uib/echo/HappeningTest.kt
Labels: patch :mag:

#312 ✨ JWT for NextAuth & Feide
  build.gradle.kts
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
Labels: feature :sparkles:

#313 add endpoint for spots count
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/SpotRange.kt
Labels: feature :sparkles:, minor :arrow_up_small:

#314 Release 7.1.0
  .env.example
  .github/workflows/cypress_test.yaml
  .github/workflows/rebase.yaml
  Dockerfile
  build.gradle.kts
  docker-compose.cypress.yaml
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  renovate.json
  src/main/kotlin/no/uib/echo/DatabaseHandler.kt
  src/main/kotlin/no/uib/echo/Email.kt
  src/main/kotlin/no/uib/echo/Response.kt
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/Answer.kt
  src/main/kotlin/no/uib/echo/schema/Happening.kt
  src/main/kotlin/no/uib/echo/schema/Registration.kt
  src/main/kotlin/no/uib/echo/schema/SpotRange.kt
  src/main/kotlin/no/uib/echo/schema/User.kt
  src/main/resources/db/migration/V14__User.sql
  src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
  src/test/kotlin/no/uib/echo/HappeningTest.kt
Labels: minor :arrow_up_small:, release :label:

#315 🐛 Fix wrong column name
  src/main/resources/db/migration/V15__Degree_year_rename.sql
Labels: bug :bug:, database :desktop_computer:, patch :mag:

#316 Release 7.1.1
  src/main/resources/db/migration/V15__Degree_year_rename.sql
Labels: patch :mag:, release :label:
