Repository echo-webkom/echo-web-backend, pull requests merged in 2022-05, with the labels that each got.

#319 🐛 Fix incorrect reference
  src/main/kotlin/no/uib/echo/Email.kt
  src/main/kotlin/no/uib/echo/schema/Happening.kt
Labels: bug :bug:, patch :mag:

#320 Release 7.1.2
  build.gradle.kts
  gradle.properties
  src/main/kotlin/no/uib/echo/Application.kt
  src/main/kotlin/no/uib/echo/Email.kt
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/Happening.kt
  src/main/kotlin/no/uib/echo/schema/Registration.kt
  src/main/kotlin/no/uib/echo/schema/SpotRange.kt
  src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
Labels: patch :mag:, release :label:

#321 Add waitlist as field at regcount endpoint
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/SpotRange.kt
Labels: feature :sparkles:, minor :arrow_up_small:

#322 Add waitlist count to reg count endpoint
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/SpotRange.kt
Labels: feature :sparkles:, minor :arrow_up_small:, release :label:

#323 Fix/vedtektsendringer
  README.md
  src/main/kotlin/no/uib/echo/Response.kt
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/Degree.kt
  src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
Labels: patch :mag:

#324 Release 7.2.1
  README.md
  src/main/kotlin/no/uib/echo/Response.kt
  src/main/kotlin/no/uib/echo/plugins/Routing.kt
  src/main/kotlin/no/uib/echo/schema/Degree.kt
  src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
Labels: patch :mag:, release :label:
